name: auth
description: "A new Flutter package project."
version: 0.0.2
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
  ui_kit:
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  http: ^1.6.0
  fpdart: ^1.2.0
  firebase_auth: ^6.1.2
  get_it: ^9.1.1
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter:
  uses-material-design: true