name: core
description: "Shared utilities and extensions."
version: 0.0.2
resolution: workspace
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  http: ^1.6.0
  get_it: ^9.1.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4